// GENERATED by meatball-labs/family/build.py from family.json. Do not edit;
// resync with the site's sync script.

export type FamilyHue = "clay" | "ochre" | "moss" | "sage" | "spruce" | "steel" | "iris" | "plum" | "rose"

export interface FamilyMember {
  hue: FamilyHue
  hex: string
  name?: string
  href?: string
  role?: "lab" | "home"
  /** A hue held for a site that is not answering yet: named, not linked. */
  reserved?: boolean
}

export const FAMILY_LABEL = "Meatball Labs and family"

/** The colour wheel, warm to cool. Fixed order; a new site takes an open hue. */
export const FAMILY: readonly FamilyMember[] = [
  { hue: "clay", hex: "#995d48", name: "Meatball Labs", href: "https://meatball.ai", role: "lab" },
  { hue: "ochre", hex: "#89692f", name: "SysForge", href: "https://sysforge.ai", role: "lab" },
  { hue: "moss", hex: "#68763a" },
  { hue: "sage", hex: "#427d59", name: "hotbits", href: "https://tinymachines.ai/hotbits", role: "lab" },
  { hue: "spruce", hex: "#1b7d82", name: "amy.io", href: "https://amy.io", role: "lab" },
  { hue: "steel", hex: "#41749d", name: "bradley.io", href: "https://bradley.io", role: "home" },
  { hue: "iris", hex: "#6a679e", name: "tinymachines.ai", href: "https://tinymachines.ai", role: "lab" },
  { hue: "plum", hex: "#8b5c86", name: "Campaign Brain", href: "https://campaignbrain.dev", role: "lab" },
  { hue: "rose", hex: "#995963", name: "snailmail.ai", role: "lab", reserved: true },
]
