#!/usr/bin/env python3
"""Derive tokens.static.css (a :root block) from tokens.css (an @theme block).

The zoo is a plain HTML page with no build step, so it cannot read @theme.
Rather than keep a second hand-maintained copy of the palette (which is
exactly how the ten nav lists in the 6502 repo drifted three ways), the
standalone file is generated. Never edit tokens.static.css by hand.

    python3 build-tokens.py
"""
import re, pathlib, sys

src = pathlib.Path("tokens.css").read_text()
m = re.search(r"@theme\s*\{(.*?)\n\}", src, re.S)
if not m:
    sys.exit("no @theme block found in tokens.css")

body = m.group(1)
body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)          # strip comments first
decls = [(k, " ".join(v.split()))                             # multi-line values collapse
         for k, v in re.findall(r"(--[\w-]+)\s*:\s*([^;]+);", body)]
if not decls:
    sys.exit("no declarations found")

out = [
    "/* GENERATED by build-tokens.py from tokens.css. Do not edit. */",
    ":root {",
]
out += [f"  {k}: {v};" for k, v in decls]
out += ["}", ""]

pathlib.Path("tokens.static.css").write_text("\n".join(out))
print(f"tokens.static.css: {len(decls)} tokens")
