/**
 * Generate public/sw.js, stamped with the commit it was built from.
 *
 * Generated rather than committed for one reason that is not tidiness: **a
 * browser installs a new service worker only when the file's BYTES change.**
 * A hand-written sw.js never changes, so the first one a visitor installs is
 * the one they keep, and every cache it holds is held forever with no
 * server-side way to reach it. Stamping the commit makes a deploy a new
 * worker, and the new worker deletes the old caches on activate.
 *
 * That is the same failure this site already paid for once at the HTTP layer,
 * when a 404 for a /_next/static chunk was cached for a year with
 * `immutable` and the symptom was a page with no stylesheet. A service worker
 * is that bug with a longer memory: nothing at the origin can evict it.
 *
 * Run from `bun run build`, before next build, so the worker is in public/
 * when Next copies it.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const ROOT = path.join(import.meta.dirname, "..", "..");
const OUT = path.join(import.meta.dirname, "..", "public", "sw.js");

/**
 * The commit, read out of .git directly.
 *
 * Not by shelling out to git: a build run by a deploy inherits systemd's PATH,
 * which need not have git on it. api/provenance.py reads it the same way for
 * the same reason.
 */
async function commit() {
  try {
    const head = (await readFile(path.join(ROOT, ".git", "HEAD"), "utf8")).trim();
    if (!head.startsWith("ref:")) return head.slice(0, 12);
    const ref = head.slice(4).trim();
    try {
      return (await readFile(path.join(ROOT, ".git", ref), "utf8")).trim().slice(0, 12);
    } catch {
      // A packed ref: the loose file does not exist after `git gc`.
      const packed = await readFile(path.join(ROOT, ".git", "packed-refs"), "utf8");
      const line = packed.split("\n").find((l) => l.endsWith(" " + ref));
      return line ? line.slice(0, 12) : null;
    }
  } catch {
    return null;
  }
}

const version = (await commit()) ?? "unversioned";
if (version === "unversioned") {
  // Not fatal: a tarball with no .git still has to build. But it is worth
  // saying, because a worker that never changes version is a worker whose
  // caches are never purged.
  console.warn("build-sw: no .git, so the worker is 'unversioned' and a deploy will not purge its caches.");
}

const sw = `/* tinymachines.ai service worker. GENERATED by scripts/build-sw.mjs.
 *
 * Built from ${version}. Do not edit: the next build overwrites it, and the
 * version stamp is what makes a deploy replace the worker at all.
 *
 * The whole design is one rule: **cache only what cannot change.**
 *
 * This repository has already paid for the other kind. A 404 for a
 * /_next/static chunk was once served with "immutable" and cached for a year,
 * and the symptom was a site with no stylesheet, which reads as a design that
 * was never applied rather than as a caching fault. A service worker is that
 * bug with a longer memory and no server-side way to reach it, so the rules
 * below are deliberately narrow and every exception is named.
 */

const VERSION = ${JSON.stringify(version)};
const ASSETS = "tm-assets-" + VERSION;   // immutable, content-hashed things
const PAGES = "tm-pages-" + VERSION;     // last-known-good HTML, for offline only

/* Content-hashed by the build, so the bytes at one of these URLs can never
 * change. Cache-first is safe by construction rather than by policy. */
const IMMUTABLE = /^\\/_next\\/static\\//;

/* Never touched, and each for its own reason.
 *   /api/       live state, and /v1/status is a measurement. A cached
 *               measurement is a lie with a timestamp on it.
 *   /admin      credentials and people's addresses. Nothing about that page
 *               belongs in a cache on somebody's disk.
 *   /sw.js      the worker caching itself is how a bad worker becomes
 *               permanent. */
const NEVER = [/^\\/api\\//, /^\\/admin(\\/|$)/, /^\\/sw\\.js$/];

self.addEventListener("install", () => {
  /* No precache list. A precache is a promise that a set of URLs is worth
   * holding before anybody has asked for one, and getting it wrong means
   * shipping bytes nobody uses and holding a version nobody is on. What this
   * worker caches, it caches because the page actually asked for it. */
  self.skipWaiting();
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    /* Delete every cache from another version. This is the line that makes
     * the version stamp worth having: without it a deploy leaves the previous
     * build's assets on disk forever. */
    const keep = new Set([ASSETS, PAGES]);
    await Promise.all((await caches.keys()).map((k) => (keep.has(k) ? null : caches.delete(k))));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);

  /* Cross-origin is not ours. The console and the lab both fetch the chip API
   * on 6502.tinymachines.ai, and a worker that intercepted those would be
   * caching the state of a machine. */
  if (url.origin !== self.location.origin) return;
  if (NEVER.some((re) => re.test(url.pathname))) return;

  if (IMMUTABLE.test(url.pathname)) {
    e.respondWith((async () => {
      const hit = await caches.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      /* Only a real 200 is stored. Caching a 404 under an immutable rule is
       * exactly the bug named at the top of this file. */
      if (res.ok && res.status === 200) (await caches.open(ASSETS)).put(req, res.clone());
      return res;
    })());
    return;
  }

  /* Documents: network first, always. The cache is a fallback for being
   * offline and never a source of truth, so a deploy is visible on the next
   * load rather than whenever a cache happens to expire. */
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        const res = await fetch(req);
        if (res.ok) (await caches.open(PAGES)).put(req, res.clone());
        return res;
      } catch (err) {
        const hit = await caches.match(req);
        if (hit) return hit;
        const home = await caches.match("/");
        if (home) return home;
        throw err;
      }
    })());
  }
});
`;

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, sw);
console.log(`build-sw: public/sw.js from ${version}`);
