"use client";

import { useEffect } from "react";

/**
 * Registers the service worker, which is what makes the site installable and
 * makes it open offline.
 *
 * Registered from the app rather than by an inline script, so it happens once
 * on the client after hydration and never during a prerender. There is nothing
 * for the server to do here and nothing on the page depends on it: the site
 * works exactly the same if this never runs, which is the property that makes
 * it safe to add to every page.
 *
 * `/sw.js` is generated by scripts/build-sw.mjs and stamped with the commit,
 * because a browser installs a new worker only when the file's bytes change. A
 * hand-written worker never changes, so the first one a visitor installs is
 * the one they keep forever, and nothing at the origin can evict it.
 *
 * Failures are swallowed, and that is not laziness. Registration fails in a
 * private window, on an insecure origin, and wherever a user or an enterprise
 * policy has turned workers off, and none of those is something a reader
 * should be told about at the bottom of a page they came to read. The site
 * degrades to a site.
 */
export function ServiceWorker() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;
    // After load, so registration never competes with the first paint for
    // bandwidth on the visit that matters most.
    // updateViaCache: "none" is a fix, not a default. The apex nginx maps
    // *.js to "public, max-age=3600", so /sw.js is an asset like any other as
    // far as the origin is concerned, and a browser holding it for an hour is
    // a browser running the previous deploy's worker for an hour. This makes
    // the update check always go to the network for the worker and anything
    // it imports.
    //
    // The alternative is a no-cache rule for /sw.js in the apex config, which
    // is the tidier place for it and costs an nginx reload across every vhost
    // on this box. Worth doing next time that file is opened for another
    // reason; not worth a server-wide reload on its own.
    const go = () =>
      navigator.serviceWorker.register("/sw.js", { updateViaCache: "none" }).catch(() => {});
    if (document.readyState === "complete") go();
    else window.addEventListener("load", go, { once: true });
  }, []);

  return null;
}
