import type { MetadataRoute } from "next";
import { token } from "@/lib/tokens";

/**
 * The web app manifest, which is what makes this installable.
 *
 * Generated by Next from this file rather than dropped in public/, for the
 * reason app/robots.ts is: the two colours below come out of style/tokens.css
 * at build time, and a manifest with a hand-typed theme colour is a second
 * copy of the palette that nothing re-derives. An install banner one revision
 * behind the tokens looks exactly like an install banner.
 *
 * Four decisions are in here.
 *
 * `display: standalone` rather than `fullscreen`. This is a documentation site
 * with two instruments on it, not a game: taking the status bar away from a
 * reader buys nothing and costs them the clock.
 *
 * `start_url: "/"`, not the last page visited. An installed icon should open
 * the front door.
 *
 * `theme_color` is the ink rather than the paper. It colours the system bars
 * around the app, and STYLE.md's two grounds make ink the frame and paper the
 * page: a paper-coloured system bar would make the app look like it had no
 * chrome at all on a light phone.
 *
 * `background_color` is the paper, because it is what the splash screen shows
 * before the first paint, and the first paint is a paper page.
 *
 * The icons come from style/build-icon.py, which draws them from the same
 * tokens. The maskable one is drawn smaller so the mark survives whatever
 * shape a launcher crops it into; build-icon.py has the arithmetic.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "tinymachines",
    short_name: "tinymachines",
    description: "A transistor-level MOS 6502, and the things built on it.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "any",
    background_color: token("color-paper"),
    theme_color: token("color-ink"),
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
