import type { MetadataRoute } from "next";
import { abs } from "@/lib/seo";

/**
 * robots.txt, generated by Next rather than dropped in public/.
 *
 * Three decisions are in here and each one has a reason worth keeping, because
 * a robots file is exactly the kind of thing that gets copied between projects
 * and then means something different than the person copying it thought.
 *
 * (Written without bold markers around paths, because "**" followed by a path
 * beginning with a slash closes a block comment. The first version of this
 * file ended halfway through its own explanation.)
 *
 * The zoo route is deliberately NOT disallowed, even though it should not
 * appear in a search result. It carries `robots: noindex, nofollow` in its own
 * metadata, and the two mechanisms do not stack: Disallow stops a crawler
 * FETCHING the page, so it never sees the noindex, and the URL can still end up
 * listed from inbound links with no description. Allowing the fetch is what
 * makes the noindex effective. Disallow here would quietly defeat it.
 *
 * The API prefix IS disallowed because it is a surface, not content. Nothing under
 * it is a page, indexing JSON helps nobody, and /v1/status makes outbound
 * requests to the three live subdomains when its cache is cold. That is
 * bounded to one probe per piece per 30 seconds, so a crawler could not do
 * real damage, but there is no reason to spend somebody else's bandwidth on
 * crawl budget. `openapi.json` stays reachable and is linked from `GET /api/`.
 *
 * The Sitemap line points at app/sitemap.ts, which is generated from the
 * same sources the pages are (the docs tree, the explorer's page list), not
 * hand written, for the same reason the navigation is.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: "/", disallow: ["/api/"] }],
    sitemap: abs("/sitemap.xml"),
  };
}
