import { chromium } from "@playwright/test";
const out = "/tmp/claude-1000/-home-bisenbek-projects-tinymachines-public/df49fc18-048e-47c2-bff3-d6689888b0f0/scratchpad/lab";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
await p.goto("https://tinymachines.ai/6502/tracer/article", { waitUntil: "networkidle" });
await p.waitForTimeout(2000);
await p.evaluate(() => scrollTo(0, document.documentElement.scrollHeight));
await p.waitForTimeout(500);
await p.screenshot({ path: `${out}/art-bottom.png` });
await p.screenshot({ path: `${out}/art-top.png`, clip: { x: 0, y: 0, width: 390, height: 844 } });
console.log(JSON.stringify(await p.evaluate(() => [...document.querySelectorAll("footer, .site-foot, .art-return")].map((e) => ({ cls: e.className, top: Math.round(e.getBoundingClientRect().top + scrollY), h: Math.round(e.getBoundingClientRect().height), parent: e.parentElement.className })))));
await b.close();
