import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Die Runner's modules, copied byte for byte from tinymachines/6502 apart
    // from one documented line. They are vanilla ES modules and the console is
    // tested where it lives, so linting them here buys nothing and costs the
    // property that makes the copy trustworthy: react-hooks/rules-of-hooks
    // fires on a plain function called useCart(), and "fixing" that would mean
    // renaming a function in a file whose whole value is being identical to
    // the original. A fork starts with one rename.
    //
    // public/engine/ is deliberately NOT ignored: tm6502.mjs is written here.
    "public/6502/games/**",

    // The lab's stylesheet and script, GENERATED by scripts/build-lab.mjs from
    // the 6502 checkout's Lab. Linting a derived copy of somebody else's file
    // reports twenty warnings that can only be fixed by editing the original,
    // and the original is not ours to tidy.
    "public/6502/lab/**",

    // The bench's wasm glue, GENERATED by wasm-bindgen at the boarded commit
    // (scripts/board-ntsc.py --wasm) and pinned by hash in data/ntsc.json.
    // Same reasoning as the lab: its warnings are wasm-bindgen's to fix, and
    // an edit here would break the hash that makes the bundle trustworthy.
    // public/ntsc/bench.worker.mjs is ours and deliberately NOT ignored.
    "public/ntsc/wasm/**",

    // The console's wasm glue and the playground's chips, GENERATED by
    // wasm-bindgen (scripts/board-nes.py --wasm, scripts/build-playground-wasm.py)
    // and gitignored. Same reasoning again: wasm-bindgen's warnings, and a
    // hash that an edit would break.
    "public/nes/wasm/**",
    "public/nes/flow/**",
    "public/nes/listing/**",
    "public/nes/slow/**",
    "public/nes/voices/**",

    // pretext's bundle, GENERATED by scripts/build-pretext.mjs from the
    // submodule's TypeScript and gitignored. lib/vendor/pretext.d.ts, the
    // hand-written typed surface, is ours and stays linted.
    "lib/vendor/pretext.js",
  ]),
  {
    rules: {
      // A name that starts with an underscore is unused on purpose: a
      // destructuring that drops fields, a parameter a signature requires.
      // Saying so in the name is the convention; the rule should read it.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_", destructuredArrayIgnorePattern: "^_" },
      ],
    },
  },
]);

export default eslintConfig;
